const LANG = {
  hy: {
    welcome: 'Բարի գալուստ Travel Bot: Օգտվելու համար սեղմիր ստորևի կոճակը:',
    newRequest: '✈️ Նոր ուղևորություն',
    becomeAgent: '💼 Դառնալ տուր ագենտ',
    agentRegister: 'Գրանցվել որպես տուր ագենտ',
    sendRequest: '🔍 Ուղարկել հայտ',
    langSelect: 'Ընտրիր լեզուն / Choose language / Выберите язык:',
    country: '🌍 Ո՞ր երկիր ես ուզում գնալ:',
    weekend: '📅 Ո՞ր հանգստյան օրերն ես նախընտրում:',
    flightDate: '✈️ Նշիր թռիչքի ցանկալի ամսաթիվը:',
    people: '👥 Քանի՞ հոգի եք:',
    budget: '💰 Մոտավոր բյուջե (մեկ անձի համար, USD):',
    notes: '📝 Լրացուցիչ նշումներ (կամ գրիր «ոչ»):',
    confirmRequest: 'Հաստատե՞լ ուղևորության հայտը:',
    requestSent: '✅ Ձեր հայտը ուղարկվել է բոլոր տուր ագենտներին: Սպասեք պատասխանի:',
    requestDetails: '📋 Ուղևորության հայտ #%d\n\n🌍 Երկիր: %s\n📅 Հանգստյան օրեր: %s\n✈️ Թռիչք: %s\n👥 Մարդ: %d\n💰 Բյուջե: %s\n📝 Նշում: %s',
    newRequestForAgent: '📩 Նոր ուղևորության հայտ #%d\n\n👤 Հաճախորդ: %s\n🌍 Երկիր: %s\n📅 Հանգստյան օրեր: %s\n✈️ Թռիչք: %s\n👥 Մարդ: %d\n💰 Բյուջե: %s\n📝 Նշում: %s\n\nՊատասխանելու համար սեղմիր ստորևի կոճակը:',
    respond: '📩 Պատասխանել',
    yourResponse: '✍️ Գրիր քո առաջարկը (գին + նկարագրություն):',
    responseSent: '✅ Ձեր պատասխանն ուղարկվել է հաճախորդին:',
    responseFromAgent: '📩 Պատասխան տուր ագենտից %s (%s)\n\n💰 Գին: %s\n📝 %s',
    noRequests: 'Դեռ ուղևորության հայտեր չկան:',
    registerPrompt: 'Գրանցվելու համար գրիր твоё имя, компания и телефон:\nՕրինակ՝ Արմեն, TravelPro, +37455123456',
    registerSuccess: '✅ Ձեր գրանցման հայտն ուղարկվել է: Սպասեք հաստատման:',
    approved: '✅ Դուք հաստատվել եք որպես տուր ագենտ: Այժմ կստանաք հաճախորդների հայտերը:',
    cancel: '❌ Չեղարկել',
    back: '🔙 Հետ',
    error: '❌ Սխալ: Կրկին փորձեք:',
    notAgent: 'Դուք գրանցված չեք որպես տուր ագենտ: Գրանցվելու համար գրեք /register:',
  },
  en: {
    welcome: 'Welcome to Travel Bot! Click the button below to start.',
    newRequest: '✈️ New Trip',
    becomeAgent: '💼 Become a Tour Agent',
    agentRegister: 'Register as Tour Agent',
    sendRequest: '🔍 Send Request',
    langSelect: 'Choose language / Ընտրիր լեզուն / Выберите язык:',
    country: '🌍 Which country do you want to visit?',
    weekend: '📅 Which weekend dates do you prefer?',
    flightDate: '✈️ Enter your preferred flight date:',
    people: '👥 How many people?',
    budget: '💰 Approximate budget (per person, USD):',
    notes: '📝 Additional notes (or type "none"):',
    confirmRequest: 'Confirm travel request?',
    requestSent: '✅ Your request has been sent to all tour agents. Waiting for responses.',
    requestDetails: '📋 Travel Request #%d\n\n🌍 Country: %s\n📅 Weekends: %s\n✈️ Flight: %s\n👥 People: %d\n💰 Budget: %s\n📝 Notes: %s',
    newRequestForAgent: '📩 New Travel Request #%d\n\n👤 Client: %s\n🌍 Country: %s\n📅 Weekends: %s\n✈️ Flight: %s\n👥 People: %d\n💰 Budget: %s\n📝 Notes: %s\n\nClick the button below to respond:',
    respond: '📩 Respond',
    yourResponse: '✍️ Write your offer (price + description):',
    responseSent: '✅ Your response has been sent to the client.',
    responseFromAgent: '📩 Response from agent %s (%s)\n\n💰 Price: %s\n📝 %s',
    noRequests: 'No travel requests yet.',
    registerPrompt: 'To register, enter: name, company, phone:\nExample: John, TravelPro, +1234567890',
    registerSuccess: '✅ Your registration has been submitted. Waiting for approval.',
    approved: '✅ You have been approved as a tour agent. You will now receive client requests.',
    cancel: '❌ Cancel',
    back: '🔙 Back',
    error: '❌ Error. Please try again.',
    notAgent: 'You are not registered as a tour agent. Send /register to sign up.',
  },
  ru: {
    welcome: 'Добро пожаловать в Travel Bot! Нажмите кнопку ниже, чтобы начать.',
    newRequest: '✈️ Новая поездка',
    becomeAgent: '💼 Стать тур агентом',
    agentRegister: 'Зарегистрироваться как тур агент',
    sendRequest: '🔍 Отправить заявку',
    langSelect: 'Выберите язык / Choose language / Ընտրիր լեզուն:',
    country: '🌍 В какую страну хотите поехать?',
    weekend: '📅 Какие выходные дни предпочитаете?',
    flightDate: '✈️ Укажите желаемую дату вылета:',
    people: '👥 Сколько человек?',
    budget: '💰 Примерный бюджет (на человека, USD):',
    notes: '📝 Дополнительные заметки (или напишите "нет"):',
    confirmRequest: 'Подтвердить заявку?',
    requestSent: '✅ Ваша заявка отправлена всем тур агентам. Ожидайте ответа.',
    requestDetails: '📋 Заявка #%d\n\n🌍 Страна: %s\n📅 Выходные: %s\n✈️ Вылет: %s\n👥 Людей: %d\n💰 Бюджет: %s\n📝 Заметки: %s',
    newRequestForAgent: '📩 Новая заявка #%d\n\n👤 Клиент: %s\n🌍 Страна: %s\n📅 Выходные: %s\n✈️ Вылет: %s\n👥 Людей: %d\n💰 Бюджет: %s\n📝 Заметки: %s\n\nНажмите кнопку ниже, чтобы ответить:',
    respond: '📩 Ответить',
    yourResponse: '✍️ Напишите ваше предложение (цена + описание):',
    responseSent: '✅ Ваш ответ отправлен клиенту.',
    responseFromAgent: '📩 Ответ от агента %s (%s)\n\n💰 Цена: %s\n📝 %s',
    noRequests: 'Пока нет заявок.',
    registerPrompt: 'Для регистрации укажите: имя, компания, телефон:\nПример: Иван, TravelPro, +37455123456',
    registerSuccess: '✅ Ваша регистрация отправлена. Ожидайте подтверждения.',
    approved: '✅ Вы утверждены как тур агент. Теперь вы будете получать заявки клиентов.',
    cancel: '❌ Отмена',
    back: '🔙 Назад',
    error: '❌ Ошибка. Попробуйте снова.',
    notAgent: 'Вы не зарегистрированы как тур агент. Отправьте /register для регистрации.',
  },
};

function t(lang, key, ...args) {
  let str = (LANG[lang] || LANG.en)[key] || key;
  if (args.length > 0) str = str.replace(/%[sd]/g, () => args.shift());
  return str;
}

module.exports = { t, LANG };
